# Generated by Django 4.2.7 on 2023-11-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('E', 'Earned'), ('P', 'Passive'), ('A', 'Porfolio')], default='E', max_length=1)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
