# Generated by Django 4.2.7 on 2023-11-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Earned', 'Earned'), ('Passive', 'Passive'), ('Portfolio', 'Porfolio')], default='Earned', max_length=100),
        ),
    ]
